### ISSUE TITLE
SrapiV4 - ContentTypeBuilder - create new collection - bug

### ISSUE THREAD

**Issue by godzzo** [akcyp/strapi-plugin-point-list#2]
## Description

I could not create a Collection after I setup the point list plugin.

### Secreenshot / Reference

[props](https://github.com/akcyp/strapi-plugin-point-list/blob/9373ee8eae8c4d0680c49bad22e86b664d5b046c/admin/src/index.js#L15)

![image](https://user-images.githubusercontent.com/912200/153825360-6ef39d32-5f4d-4181-90b0-b4a3f795e22c.png)

### Chrome Console log

```
main.bundle.js:57546 Uncaught TypeError: Cannot read properties of undefined (reading 'fieldRenderer')
    at main.bundle.js:57546:30
    at root.<computed> (main.bundle.js:57652:15)
    at renderWithHooks (main.bundle.js:142101:18)
    at mountIndeterminateComponent (main.bundle.js:144927:13)
    at beginWork (main.bundle.js:146165:16)
    at HTMLUnknownElement.callCallback (main.bundle.js:131061:14)
    at Object.invokeGuardedCallbackDev (main.bundle.js:131110:16)
    at invokeGuardedCallback (main.bundle.js:131172:31)
    at beginWork$1 (main.bundle.js:151075:7)
    at performUnitOfWork (main.bundle.js:149887:12)
```

## Suggestion

Handle undefined `attribute` property.

```js
intercept(helperPlugin, 'GenericInput', ({ args: [props], resolve }) => {
  const type = (props.attribute || {}).fieldRenderer || props.type;
  return resolve({
    ...props,
    type,
  });
});
```

**Comment by akcyp** [comment]
I didn't notice this error during migration, thanks for the quick fix of the code
